### PR TITLE
Improve meson integration and project structure

### PR DESCRIPTION
**Pull request by NathanBnm**
I improved the way your app is built with meson.
App is building and working fine on my side.

### CODE REVIEW

**Comment by eudaldgr** [comment]
i don't like it.

**Comment by NathanBnm** [comment]
Why that? Lots of elementary apps are adopting this particular structure.

This is making the app structure more clear and understandable for developers by separating code, using appropriate file ans variables names, etc

You cannot say that without any justification 🤔

**Comment by NathanBnm** [comment]
I don't see the point if you're just rolling back my changes 🤔

**Comment by eudaldgr** [comment]
I have not changed everything. The point is that I accept your changes, but not 100%. if you don't like make your own app, this is mine

**Pull request merged**
